### ISSUE TITLE
复发后看不到返回的数据

### ISSUE THREAD

**Issue by lonleylkk** [xuanyanwow/easyswooleHttpMonitor#2]
运行环境:macOs php72 swoole4.4.4 easyswoole3.3.0
复发请求看不到返回信息

end方法貌似只用于设置结束响应的状态,并不返回
把end里面的数据放到write里面之后才能看到返回的信息
`$response->write(Monitor::getInstance()->resend($content['id']));`

**Comment by xuanyanwow** [comment]
文档说明已更正，swoole原生Response类的end方法可以返回消息，es封装后要使用write
